name: capstone-ci
on:
  workflow_dispatch: # For debugging
  pull_request:
    branches:
    - main
    - dev

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install dependencies
        run: |
          bundle install
          sudo apt-get install --yes --quiet libsqlite3-dev # Required due to SQLite3 database
          steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn
      - name: lint
        run: bundle exec rubocop --auto-correct --cache=true
      - name: test # Always run tests AFTER linting
        run: | # https://anthonybroadcrawford.com/2020/03/02/webpacker-heroku-ci.html
          bundle exec rails assets:precompile
          bundle exec rails test
